// Mocks generated by Mockito 5.3.2 from annotations
// in mc_crud_test/test/features/customer/domain/repositories/customer_database_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mc_crud_test/features/customer/data/datasources/create_customer_request.dart'
    as _i6;
import 'package:mc_crud_test/features/customer/data/models/customer_model.dart'
    as _i5;
import 'package:mc_crud_test/features/customer/data/repositories/customer_database_service_impl.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_1 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CustomerDatabaseServiceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerDatabaseServiceImpl extends _i1.Mock
    implements _i3.CustomerDatabaseServiceImpl {
  MockCustomerDatabaseServiceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Database get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDatabase_0(
          this,
          Invocation.getter(#db),
        ),
      ) as _i2.Database);
  @override
  set db(_i2.Database? _db) => super.noSuchMethod(
        Invocation.setter(
          #db,
          _db,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<int?> deleteCustomer(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCustomer,
          [id],
        ),
        returnValue: _i4.Future<int?>.value(),
      ) as _i4.Future<int?>);
  @override
  _i4.Future<List<_i5.CustomerModel>> getAllCustomers() => (super.noSuchMethod(
        Invocation.method(
          #getAllCustomers,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.CustomerModel>>.value(<_i5.CustomerModel>[]),
      ) as _i4.Future<List<_i5.CustomerModel>>);
  @override
  _i4.Future<_i5.CustomerModel?> getCustomer(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getCustomer,
          [id],
        ),
        returnValue: _i4.Future<_i5.CustomerModel?>.value(),
      ) as _i4.Future<_i5.CustomerModel?>);
  @override
  _i4.Future<_i5.CustomerModel?> insertCustomer(
          _i6.CreateCustomerRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertCustomer,
          [request],
        ),
        returnValue: _i4.Future<_i5.CustomerModel?>.value(),
      ) as _i4.Future<_i5.CustomerModel?>);
  @override
  _i4.Future<int?> updateCustomer(_i5.CustomerModel? customer) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCustomer,
          [customer],
        ),
        returnValue: _i4.Future<int?>.value(),
      ) as _i4.Future<int?>);
  @override
  _i4.Future<dynamic> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);
}

/// A class which mocks [CustomerModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerModel extends _i1.Mock implements _i5.CustomerModel {
  MockCustomerModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set id(int? _id) => super.noSuchMethod(
        Invocation.setter(
          #id,
          _id,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set firstName(String? _firstName) => super.noSuchMethod(
        Invocation.setter(
          #firstName,
          _firstName,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set lastName(String? _lastName) => super.noSuchMethod(
        Invocation.setter(
          #lastName,
          _lastName,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set dateOfBirth(DateTime? _dateOfBirth) => super.noSuchMethod(
        Invocation.setter(
          #dateOfBirth,
          _dateOfBirth,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set phoneNumber(String? _phoneNumber) => super.noSuchMethod(
        Invocation.setter(
          #phoneNumber,
          _phoneNumber,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set email(String? _email) => super.noSuchMethod(
        Invocation.setter(
          #email,
          _email,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set bankAccountNumber(String? _bankAccountNumber) => super.noSuchMethod(
        Invocation.setter(
          #bankAccountNumber,
          _bankAccountNumber,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
  @override
  String get fullName => (super.noSuchMethod(
        Invocation.getter(#fullName),
        returnValue: '',
      ) as String);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
  @override
  Map<String, dynamic> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [CreateCustomerRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateCustomerRequest extends _i1.Mock
    implements _i6.CreateCustomerRequest {
  MockCreateCustomerRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get firstName => (super.noSuchMethod(
        Invocation.getter(#firstName),
        returnValue: '',
      ) as String);
  @override
  String get lastName => (super.noSuchMethod(
        Invocation.getter(#lastName),
        returnValue: '',
      ) as String);
  @override
  DateTime get dateOfBirth => (super.noSuchMethod(
        Invocation.getter(#dateOfBirth),
        returnValue: _FakeDateTime_1(
          this,
          Invocation.getter(#dateOfBirth),
        ),
      ) as DateTime);
  @override
  String get phoneNumber => (super.noSuchMethod(
        Invocation.getter(#phoneNumber),
        returnValue: '',
      ) as String);
  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: '',
      ) as String);
  @override
  String get bankAccountNumber => (super.noSuchMethod(
        Invocation.getter(#bankAccountNumber),
        returnValue: '',
      ) as String);
  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
  @override
  Map<String, dynamic> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
