// Mocks generated by Mockito 5.3.2 from annotations
// in mc_crud_test/test/features/customer/presentation/bloc/customer/customer_form_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:either_dart/either.dart' as _i3;
import 'package:mc_crud_test/core/error/failures.dart' as _i8;
import 'package:mc_crud_test/features/customer/data/datasources/create_customer_request.dart'
    as _i10;
import 'package:mc_crud_test/features/customer/data/datasources/update_customer_request.dart'
    as _i13;
import 'package:mc_crud_test/features/customer/data/models/customer_model.dart'
    as _i9;
import 'package:mc_crud_test/features/customer/domain/repositories/create_customer_repository.dart'
    as _i2;
import 'package:mc_crud_test/features/customer/domain/repositories/delete_customer_repository.dart'
    as _i5;
import 'package:mc_crud_test/features/customer/domain/repositories/update_customer_repository.dart'
    as _i4;
import 'package:mc_crud_test/features/customer/domain/usecases/create_customer_usecase.dart'
    as _i6;
import 'package:mc_crud_test/features/customer/domain/usecases/delete_customer_usecase.dart'
    as _i12;
import 'package:mc_crud_test/features/customer/domain/usecases/update_customer_usecase.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCreateCustomerRepository_0 extends _i1.SmartFake
    implements _i2.CreateCustomerRepository {
  _FakeCreateCustomerRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateCustomerRepository_2 extends _i1.SmartFake
    implements _i4.UpdateCustomerRepository {
  _FakeUpdateCustomerRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteCustomerRepository_3 extends _i1.SmartFake
    implements _i5.DeleteCustomerRepository {
  _FakeDeleteCustomerRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_4 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CreateCustomerUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateCustomerUsecase extends _i1.Mock
    implements _i6.CreateCustomerUsecase {
  MockCreateCustomerUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CreateCustomerRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCreateCustomerRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CreateCustomerRepository);
  @override
  _i7.Future<_i3.Either<_i8.Failure, _i9.CustomerModel>> call(
          _i10.CreateCustomerRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [request],
        ),
        returnValue:
            _i7.Future<_i3.Either<_i8.Failure, _i9.CustomerModel>>.value(
                _FakeEither_1<_i8.Failure, _i9.CustomerModel>(
          this,
          Invocation.method(
            #call,
            [request],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, _i9.CustomerModel>>);
}

/// A class which mocks [UpdateCustomerUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateCustomerUsecase extends _i1.Mock
    implements _i11.UpdateCustomerUsecase {
  MockUpdateCustomerUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.UpdateCustomerRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeUpdateCustomerRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.UpdateCustomerRepository);
  @override
  _i7.Future<_i3.Either<_i8.Failure, _i9.CustomerModel>> call(
          _i9.CustomerModel? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [request],
        ),
        returnValue:
            _i7.Future<_i3.Either<_i8.Failure, _i9.CustomerModel>>.value(
                _FakeEither_1<_i8.Failure, _i9.CustomerModel>(
          this,
          Invocation.method(
            #call,
            [request],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, _i9.CustomerModel>>);
}

/// A class which mocks [DeleteCustomerUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteCustomerUsecase extends _i1.Mock
    implements _i12.DeleteCustomerUsecase {
  MockDeleteCustomerUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.DeleteCustomerRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDeleteCustomerRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.DeleteCustomerRepository);
  @override
  _i7.Future<_i3.Either<_i8.Failure, bool>> call(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i7.Future<_i3.Either<_i8.Failure, bool>>.value(
            _FakeEither_1<_i8.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [id],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, bool>>);
}

/// A class which mocks [CustomerModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerModel extends _i1.Mock implements _i9.CustomerModel {
  MockCustomerModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set id(int? _id) => super.noSuchMethod(
        Invocation.setter(
          #id,
          _id,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set firstName(String? _firstName) => super.noSuchMethod(
        Invocation.setter(
          #firstName,
          _firstName,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set lastName(String? _lastName) => super.noSuchMethod(
        Invocation.setter(
          #lastName,
          _lastName,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set dateOfBirth(DateTime? _dateOfBirth) => super.noSuchMethod(
        Invocation.setter(
          #dateOfBirth,
          _dateOfBirth,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set phoneNumber(String? _phoneNumber) => super.noSuchMethod(
        Invocation.setter(
          #phoneNumber,
          _phoneNumber,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set email(String? _email) => super.noSuchMethod(
        Invocation.setter(
          #email,
          _email,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set bankAccountNumber(String? _bankAccountNumber) => super.noSuchMethod(
        Invocation.setter(
          #bankAccountNumber,
          _bankAccountNumber,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
  @override
  String get fullName => (super.noSuchMethod(
        Invocation.getter(#fullName),
        returnValue: '',
      ) as String);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
  @override
  Map<String, dynamic> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [CreateCustomerRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateCustomerRequest extends _i1.Mock
    implements _i10.CreateCustomerRequest {
  MockCreateCustomerRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get firstName => (super.noSuchMethod(
        Invocation.getter(#firstName),
        returnValue: '',
      ) as String);
  @override
  String get lastName => (super.noSuchMethod(
        Invocation.getter(#lastName),
        returnValue: '',
      ) as String);
  @override
  DateTime get dateOfBirth => (super.noSuchMethod(
        Invocation.getter(#dateOfBirth),
        returnValue: _FakeDateTime_4(
          this,
          Invocation.getter(#dateOfBirth),
        ),
      ) as DateTime);
  @override
  String get phoneNumber => (super.noSuchMethod(
        Invocation.getter(#phoneNumber),
        returnValue: '',
      ) as String);
  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: '',
      ) as String);
  @override
  String get bankAccountNumber => (super.noSuchMethod(
        Invocation.getter(#bankAccountNumber),
        returnValue: '',
      ) as String);
  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
  @override
  Map<String, dynamic> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [UpdateCustomerRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateCustomerRequest extends _i1.Mock
    implements _i13.UpdateCustomerRequest {
  MockUpdateCustomerRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: 0,
      ) as int);
  @override
  String get firstName => (super.noSuchMethod(
        Invocation.getter(#firstName),
        returnValue: '',
      ) as String);
  @override
  String get lastName => (super.noSuchMethod(
        Invocation.getter(#lastName),
        returnValue: '',
      ) as String);
  @override
  DateTime get dateOfBirth => (super.noSuchMethod(
        Invocation.getter(#dateOfBirth),
        returnValue: _FakeDateTime_4(
          this,
          Invocation.getter(#dateOfBirth),
        ),
      ) as DateTime);
  @override
  String get phoneNumber => (super.noSuchMethod(
        Invocation.getter(#phoneNumber),
        returnValue: '',
      ) as String);
  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: '',
      ) as String);
  @override
  String get bankAccountNumber => (super.noSuchMethod(
        Invocation.getter(#bankAccountNumber),
        returnValue: '',
      ) as String);
}
